name: fresher_demo_2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.7.3
  google_fonts: ^6.3.0
  dio: ^5.9.1
  path_provider: ^2.1.4
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/icons/blank.svg
    - assets/icons/eyeclose.svg
    - assets/icons/eyeopen.svg
    - assets/icons/facebook.svg
    - assets/icons/headphone.svg
    - assets/icons/search.svg
